// <auto-generated />
namespace LuccasCorpVX.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Updates3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updates3));
        
        string IMigrationMetadata.Id
        {
            get { return "202503280530189_Updates3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
